# Generated by Django 5.1.4 on 2025-01-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0003_alter_categorieevenement_evenement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acheteur', models.CharField(max_length=100)),
                ('evenement', models.CharField(max_length=100)),
                ('categorie_evenement', models.CharField(max_length=100)),
                ('prix_billet', models.ImageField(upload_to='')),
                ('nombre_places_payees', models.IntegerField()),
            ],
        ),
    ]
