# Generated by Django 5.1.4 on 2025-01-25 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0004_historique'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique',
            name='date_achat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
