# Generated by Django 5.1.4 on 2025-01-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0005_historique_date_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='acheteur',
            field=models.EmailField(max_length=254),
        ),
    ]
