# Generated by Django 5.1.4 on 2025-01-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenement', '0006_alter_historique_acheteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='prix_billet',
            field=models.IntegerField(),
        ),
    ]
